version: '3.8'
services:
        php-apache-environment: 
                container_name: youtube_clone_by_php_mysql_apache_docker
                image: php:8.0-apache
                volumes:
                        - ./php/src:/var/www/html/
                ports:
                        - 8000:80

